name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia si tu rama principal tiene otro nombre

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'  # o la versión que uses

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4️⃣ Construir el sitio Astro
      - name: Build Astro site
        run: npm run build

      # 5️⃣ Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
